packages:
  - "packages/*"
  - "packages/core"
  - "packages/shared/*"
  - "packages/agents/*"
  - "packages/automation/*"
  - "packages/generators/*"
  - "packages/trading/*"
  - "packages/market-data/*"
  - "packages/wallets/*"
  - "packages/defi/*"
  - "packages/defi/protocols/*"
  - "packages/defi/layer2/*"
  - "packages/nft/*"
  - "packages/payments/*"
  - "deploy/*"
  - "x402-deploy"
