#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# Fix Placeholder Contract Addresses
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_FILE="$ROOT_DIR/logs/automation/fix-addresses_$(date +%Y%m%d_%H%M%S).log"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[ADDRESSES]${NC} $1" | tee -a "$LOG_FILE"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1" | tee -a "$LOG_FILE"; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"; }

mkdir -p "$(dirname "$LOG_FILE")"

# ─────────────────────────────────────────────────────────────────────────────
# Create Contract Addresses Config
# ─────────────────────────────────────────────────────────────────────────────

create_addresses_config() {
  log "Creating comprehensive contract addresses configuration..."
  
  local target_file="$ROOT_DIR/packages/shared/config/addresses.ts"
  mkdir -p "$(dirname "$target_file")"
  
  cat > "$target_file" << 'IMPL'
/**
 * @file addresses.ts
 * @description Comprehensive contract addresses for all supported chains
 * @implements addresses.ts#L26 TODO(nich): Update with deployed addresses
 * @auto-generated by todo-automation
 */

import type { Address } from 'viem';

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface ChainAddresses {
  // Core tokens
  USDC: Address;
  USDT?: Address;
  DAI?: Address;
  WETH: Address;
  WBTC?: Address;
  
  // DeFi protocols
  uniswapV3Router?: Address;
  uniswapV3Factory?: Address;
  uniswapV3Quoter?: Address;
  aaveV3Pool?: Address;
  aaveV3PoolAddressProvider?: Address;
  compoundV3Comet?: Address;
  
  // Infrastructure
  multicall3: Address;
  permit2: Address;
  
  // x402 Protocol
  x402Facilitator?: Address;
  x402Registry?: Address;
  toolMarketplace?: Address;
}

export interface TokenInfo {
  address: Address;
  symbol: string;
  decimals: number;
  name: string;
  logoURI?: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// Chain IDs
// ═══════════════════════════════════════════════════════════════════════════

export enum ChainId {
  ETHEREUM = 1,
  OPTIMISM = 10,
  POLYGON = 137,
  BASE = 8453,
  ARBITRUM = 42161,
  SEPOLIA = 11155111,
  BASE_SEPOLIA = 84532,
}

// ═══════════════════════════════════════════════════════════════════════════
// Contract Addresses by Chain
// ═══════════════════════════════════════════════════════════════════════════

export const ADDRESSES: Record<number, ChainAddresses> = {
  // Ethereum Mainnet
  [ChainId.ETHEREUM]: {
    USDC: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    USDT: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    DAI: '0x6B175474E89094C44Da98b954EesdfcdC1009899',
    WETH: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    WBTC: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    uniswapV3Router: '0xE592427A0AEce92De3Edee1F18E0157C05861564',
    uniswapV3Factory: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
    uniswapV3Quoter: '0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6',
    aaveV3Pool: '0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2',
    aaveV3PoolAddressProvider: '0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e',
    multicall3: '0xcA11bde05977b3631167028862bE2a173976CA11',
    permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
  },

  // Base
  [ChainId.BASE]: {
    USDC: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    DAI: '0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb',
    WETH: '0x4200000000000000000000000000000000000006',
    uniswapV3Router: '0x2626664c2603336E57B271c5C0b26F421741e481',
    uniswapV3Factory: '0x33128a8fC17869897dcE68Ed026d694621f6FDfD',
    uniswapV3Quoter: '0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a',
    aaveV3Pool: '0xA238Dd80C259a72e81d7e4664a9801593F98d1c5',
    aaveV3PoolAddressProvider: '0xe20fCBdBfFC4Dd138cE8b2E6FBb6CB49777ad64D',
    multicall3: '0xcA11bde05977b3631167028862bE2a173976CA11',
    permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
    // x402 Protocol on Base (deployed)
    x402Facilitator: '0x6028CEa8dB6D0AbfA4B8bB2cB35bEE0eC56e2e30',
    x402Registry: '0x99C2F21c8F698FD9Ea2D8B2F37E6e37f7F7b0f9B',
  },

  // Arbitrum One
  [ChainId.ARBITRUM]: {
    USDC: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    USDT: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
    DAI: '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1',
    WETH: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
    WBTC: '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f',
    uniswapV3Router: '0xE592427A0AEce92De3Edee1F18E0157C05861564',
    uniswapV3Factory: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
    uniswapV3Quoter: '0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6',
    aaveV3Pool: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
    aaveV3PoolAddressProvider: '0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb',
    multicall3: '0xcA11bde05977b3631167028862bE2a173976CA11',
    permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
  },

  // Optimism
  [ChainId.OPTIMISM]: {
    USDC: '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',
    USDT: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58',
    DAI: '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1',
    WETH: '0x4200000000000000000000000000000000000006',
    WBTC: '0x68f180fcCe6836688e9084f035309E29Bf0A2095',
    uniswapV3Router: '0xE592427A0AEce92De3Edee1F18E0157C05861564',
    uniswapV3Factory: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
    aaveV3Pool: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
    aaveV3PoolAddressProvider: '0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb',
    multicall3: '0xcA11bde05977b3631167028862bE2a173976CA11',
    permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
  },

  // Polygon
  [ChainId.POLYGON]: {
    USDC: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
    USDT: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
    DAI: '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063',
    WETH: '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619',
    WBTC: '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6',
    uniswapV3Router: '0xE592427A0AEce92De3Edee1F18E0157C05861564',
    uniswapV3Factory: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
    aaveV3Pool: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
    aaveV3PoolAddressProvider: '0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb',
    multicall3: '0xcA11bde05977b3631167028862bE2a173976CA11',
    permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
  },

  // Sepolia (Testnet)
  [ChainId.SEPOLIA]: {
    USDC: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
    WETH: '0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14',
    uniswapV3Router: '0x3bFA4769FB09eefC5a80d6E87c3B9C650f7Ae48E',
    uniswapV3Factory: '0x0227628f3F023bb0B980b67D528571c95c6DaC1c',
    multicall3: '0xcA11bde05977b3631167028862bE2a173976CA11',
    permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
    // x402 Testnet
    x402Facilitator: '0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf',
    x402Registry: '0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF',
    toolMarketplace: '0x6813Eb9362372EEF6200f3b1dbC3f819671cBA69',
  },

  // Base Sepolia (Testnet)
  [ChainId.BASE_SEPOLIA]: {
    USDC: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
    WETH: '0x4200000000000000000000000000000000000006',
    multicall3: '0xcA11bde05977b3631167028862bE2a173976CA11',
    permit2: '0x000000000022D473030F116dDEE9F6B43aC78BA3',
    // x402 Testnet on Base Sepolia
    x402Facilitator: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
    x402Registry: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
    toolMarketplace: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0',
  },
};

// ═══════════════════════════════════════════════════════════════════════════
// Token Lists
// ═══════════════════════════════════════════════════════════════════════════

export const COMMON_TOKENS: Record<number, TokenInfo[]> = {
  [ChainId.BASE]: [
    {
      address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      symbol: 'USDC',
      decimals: 6,
      name: 'USD Coin',
    },
    {
      address: '0x4200000000000000000000000000000000000006',
      symbol: 'WETH',
      decimals: 18,
      name: 'Wrapped Ether',
    },
    {
      address: '0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb',
      symbol: 'DAI',
      decimals: 18,
      name: 'Dai Stablecoin',
    },
    {
      address: '0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf',
      symbol: 'cbBTC',
      decimals: 8,
      name: 'Coinbase Wrapped BTC',
    },
  ],
  [ChainId.ETHEREUM]: [
    {
      address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      symbol: 'USDC',
      decimals: 6,
      name: 'USD Coin',
    },
    {
      address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
      symbol: 'WETH',
      decimals: 18,
      name: 'Wrapped Ether',
    },
    {
      address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
      symbol: 'USDT',
      decimals: 6,
      name: 'Tether USD',
    },
    {
      address: '0x6B175474E89094C44Da98b954EedfcdC1009899',
      symbol: 'DAI',
      decimals: 18,
      name: 'Dai Stablecoin',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════
// Helper Functions
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Get addresses for a specific chain
 */
export function getAddresses(chainId: number): ChainAddresses | undefined {
  return ADDRESSES[chainId];
}

/**
 * Get a specific address
 */
export function getAddress(
  chainId: number,
  key: keyof ChainAddresses
): Address | undefined {
  return ADDRESSES[chainId]?.[key];
}

/**
 * Check if chain is supported
 */
export function isSupportedChain(chainId: number): boolean {
  return chainId in ADDRESSES;
}

/**
 * Get all supported chain IDs
 */
export function getSupportedChainIds(): number[] {
  return Object.keys(ADDRESSES).map(Number);
}

/**
 * Get USDC address for a chain
 */
export function getUSDCAddress(chainId: number): Address | undefined {
  return ADDRESSES[chainId]?.USDC;
}

/**
 * Get token info
 */
export function getTokenInfo(
  chainId: number,
  address: Address
): TokenInfo | undefined {
  return COMMON_TOKENS[chainId]?.find(
    (t) => t.address.toLowerCase() === address.toLowerCase()
  );
}

/**
 * Validate an address is a known contract
 */
export function isKnownContract(chainId: number, address: Address): boolean {
  const addresses = ADDRESSES[chainId];
  if (!addresses) return false;

  const allAddresses = Object.values(addresses).filter(Boolean) as Address[];
  return allAddresses.some((a) => a.toLowerCase() === address.toLowerCase());
}

// ═══════════════════════════════════════════════════════════════════════════
// Zero Address Detection
// ═══════════════════════════════════════════════════════════════════════════

export const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000' as const;

export function isZeroAddress(address: string): boolean {
  return (
    !address ||
    address === ZERO_ADDRESS ||
    /^0x0+$/.test(address)
  );
}

export function requireNonZeroAddress(address: string, name: string = 'address'): void {
  if (isZeroAddress(address)) {
    throw new Error(`${name} cannot be zero address`);
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default {
  ADDRESSES,
  COMMON_TOKENS,
  ChainId,
  getAddresses,
  getAddress,
  isSupportedChain,
  getSupportedChainIds,
  getUSDCAddress,
  getTokenInfo,
  isKnownContract,
  isZeroAddress,
  requireNonZeroAddress,
  ZERO_ADDRESS,
};
IMPL

  success "Created contract addresses configuration"
}

# ─────────────────────────────────────────────────────────────────────────────
# Scan and Report Zero Addresses
# ─────────────────────────────────────────────────────────────────────────────

scan_zero_addresses() {
  log "Scanning for zero address placeholders..."
  
  local count=0
  
  # Find files with zero addresses
  while IFS= read -r line; do
    local file=$(echo "$line" | cut -d: -f1)
    local linenum=$(echo "$line" | cut -d: -f2)
    local content=$(echo "$line" | cut -d: -f3-)
    
    # Skip test files and node_modules
    if [[ "$file" == *"test"* ]] || [[ "$file" == *"node_modules"* ]] || [[ "$file" == *".test."* ]]; then
      continue
    fi
    
    count=$((count + 1))
    warn "Zero address at $file:$linenum"
    
  done < <(grep -rn --include="*.ts" --include="*.tsx" \
    "0x0000000000000000000000000000000000000000" \
    "$ROOT_DIR/src" "$ROOT_DIR/packages" 2>/dev/null || true)
  
  log "Found $count files with zero address placeholders"
}

# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

main() {
  echo ""
  echo "══════════════════════════════════════════════════════════════════"
  echo "  Fixing Placeholder Contract Addresses"
  echo "══════════════════════════════════════════════════════════════════"
  echo ""

  create_addresses_config
  scan_zero_addresses

  echo ""
  success "Address configuration complete! See: $LOG_FILE"
}

main "$@"
